### ISSUE TITLE
[Post v1.1] Interactor guide

### ISSUE THREAD

**Issue by TiteiKo** [hanami/hanami.github.io#353] opened 2017-07-05 21:35 UTC
In the v1.1, we'll change the good practices for interactors:
* no more params in initializers (well, in fact, you can actually do what you want in initializer, but it's best if you keep it for dependency injections)
* params go through `#call`
* `#call` can now take anything as parameters, except no parameters (so the minimum declaration is `def call(*); end` and not `def call; end`

Old format (̀`#call` without parameters) will still be working (I guess we'll deprecate it in v1.2?)

**Comment by cllns** [comment] 2017-07-11 00:17
I started this with #299 but didn't complete it because I got to the testing section :)

**Comment by cllns** [comment] 2017-10-25 16:36
Duplicate of #215, which was fixed via #299.

**Closed** 2018-02-19 22:30 UTC
